// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = (function() {
    function _Class(arg) {
      this.step = arg.step;
      this.timestamp = 0;
    }

    _Class.prototype.accumulate = function(callback, timestamp) {
      while (this.timestamp < timestamp) {
        setTimeout(callback, 0);
        this.timestamp += this.step;
      }
    };

    return _Class;

  })();

}).call(this);
